<a href="https://colab.research.google.com/github/patelsantosh8493-ux/AI-Core-Reforged/blob/main/01-Numpy/02_Electric_Shop_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

sales_data = np.array([
    [12, 15,  0, 18, 14, 22, 25],  # प्रोडक्ट 0 (पंखा)
    [ 5,  8,  0,  7,  6, 12, 15],  # प्रोडक्ट 1 (कूलर)
    [20, 22,  24, 19, 21,  0,  0],  # प्रोडक्ट 2 (आयरन)
    [ 8,  9,  11,  0,  7, 10, 12],  # प्रोडक्ट 3 (मिक्सर)
    [50, 45,  48, 52, 47, 55, 60]   # प्रोडक्ट 4 (टॉर्च)
])

# ----Task - 01----
d_sum = (np.sum(sales_data,axis=0))
for i in range(len(d_sum)):
   if d_sum[i] == 0:
       print(f"in day {i+1} none product to sale")

# ----Task - 01.0 Suggest by AI----
# Task 1 का नया नंपी तरीका
zero_days = np.where(d_sum == 0) # खाली स्थान में उस 'कहाँ' वाले फंक्शन का नाम लिखो

print(f"दुकान बंद होने वाले दिनों के इंडेक्स: {zero_days[0]}")


# ----Task - 02----
p_mean = (np.mean(sales_data,axis=1))
p_sum = (np.sum(sales_data,axis=1))
for i in range(len(p_mean)):
   print(f"{i+1} Product Average Sale is {round(p_mean[i],1)}")
   print(f"{i+1} Product Sum Sale is {round(p_sum[i],1)}\n")


# ----Task - 03----
print(f"가장 ज़्यादा बिकने वाले प्रोडक्ट का इंडेक्स: {np.argmax(p_sum)}")


# ----Task - 04----
week_end = sales_data[:,5:7]
print(f"Total sales of weekend is {np.sum(week_end)}")


# ----Task - 05----
sales_data2 = sales_data.copy()
sales_data2[sales_data2 == 0] = 1
print(sales_data2)

दुकान बंद होने वाले दिनों के इंडेक्स: []
1 Product Average Sale is 15.1
1 Product Sum Sale is 106

2 Product Average Sale is 7.6
2 Product Sum Sale is 53

3 Product Average Sale is 15.1
3 Product Sum Sale is 106

4 Product Average Sale is 8.1
4 Product Sum Sale is 57

5 Product Average Sale is 51.0
5 Product Sum Sale is 357

가장 ज़्यादा बिकने वाले प्रोडक्ट का इंडेक्स: 4
Total sales of weekend is 211
[[12 15  1 18 14 22 25]
 [ 5  8  1  7  6 12 15]
 [20 22 24 19 21  1  1]
 [ 8  9 11  1  7 10 12]
 [50 45 48 52 47 55 60]]
